# -*- coding: utf-8 -*-
"""centroid_calc_colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yucRNSL4sPshdHIQgU1zwXfdbxYPwKRV

## ІНІЦІАЛІЗАЦІЯ 

Запускати один раз на початку сесії.

Після певного часу відсутності активності Гугл Колаб сервер відключається. Тому, після повторно підключення цей блок потрібно знов запустити.
"""

#@title ІНІЦІАЛІЗАЦІЯ

import sys, os

# IN_COLAB == True if Jupyter Notebook running under Google Colab
IN_COLAB = 'google.colab' in sys.modules 

if IN_COLAB:
  # Mount google drive in google colab
  from google.colab import drive
  drive.mount('/content/drive')

  # Insert the directory
  sys.path.insert(0,'/content/drive/My Drive/Colab Notebooks')

  if not 'pygeodesy' in sys.modules:
    os.system('pip install PyGeodesy')

# Import my module
from centroid_util_colab import centroid_main, working_env

w_env = working_env()
print(f'Working environment: {w_env}')

import webbrowser
from IPython.display import display

#@title Параметри розрахунків

format_pattern = [
    "46.7373, 32.8128", 
    "46,7373 / 32,8128", 
    "46.7373 32.8128"]
html_page = 'centroid_map.html'

coord_format = "46.7373, 32.8128" #@param ["46.7373, 32.8128", "46,7373 / 32,8128", "46.7373 32.8128"]
lat_lon_order = 'LatLon' #@param ['LatLon', 'LonLat']
perctl = "75" #@param [50, 65, 75, 95]
zoom_start = 17 #@param {type:"slider", min:11, max:18, step:1}

coord_format_id = format_pattern.index(coord_format)
perctl = float(perctl)

print(f'Формат координат: {coord_format}')
print(f'Ід формата координат: {coord_format_id}')
print(f'Порядок координат: {lat_lon_order}')
print(f'Персентиль: {perctl}')
print(f'Стартовий зум мапи: {zoom_start}')

"""## Зразки вхідного тексту

Десяткова крапка і кома між значеннями (**coord_format_id = 0**):

>	(44.6857, 33.56173); (44.68599, 33.56555); ...  

Десяткова кома і дріб (slash) між значеннями (**coord_format_id = 1**):

> Lorem ipsum dolor sit 46,736906/ 32,810302 adipiscin, do 46,737364/  32,812807 eiusmod ...

Десяткова крапка і пробіл (**coord_format_id = 2**):

> АБВГД 48.01388889 38.79638889 07:59 АБВГД 48.01416667 38.90555556 07:53 ...
"""

#@title СКОПІЮЙТЕ ВХІДНИЙ ТЕКСТ СЮДИ:

text = '47.600139, 37.328760 \u043F\u043E 47.601340, 37.322856' #@param {type:"string"}

text

"""## Розрахунок"""

#@title РОЗРАХУНОК
map = centroid_main(text, coord_format_id=coord_format_id, perctl=perctl, \
                    zoom_start=zoom_start, html_page=html_page)

"""## Візуалізація"""

#@title ВІЗУАЛІЗАЦІЯ
if w_env in ['jupyter-lab', 'jupyter-notebook', 'google.colab']:
    display(map)
else:
    webbrowser.open(html_page)