# -*- coding: utf-8 -*-
"""centroid_calc_colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yucRNSL4sPshdHIQgU1zwXfdbxYPwKRV

## ІНІЦІАЛІЗАЦІЯ 

Запускати один раз на початку сесії.

Після певного часу відсутності активності Гугл Колаб сервер відключається. Тому, після повторно підключення цей блок потрібно знов запустити.
"""

## ІНІЦІАЛІЗАЦІЯ

import sys
LoM = sys.modules # List of Modules
# IN_COLAB == True if Jupyter Notebook running under Google Colab
IN_COLAB = 'google.colab' in LoM 
print(f'IN_COLAB = {IN_COLAB}')

LoNM = ['pygeodesy', 'centroidutilcolab'] # List of Needed Modules
if not all(m in LoM  for m in LoNM):
  print('NOT all the needed modules imported')
  !pip install PyGeodesy
  import pygeodesy
  !curl -L -o centroidutilcolab.py https://raw.githubusercontent.com/protw/airscape/master/stavok/gis/centroid/centroid_util_colab.py
else:
  print('All the needed modules imported')

from centroidutilcolab import centroid_main

#@title Параметри розрахунків

format_pattern = [
    "46.7373, 32.8128", 
    "46,7373 / 32,8128", 
    "46.7373 32.8128"]

coord_format = "46.7373, 32.8128" #@param ["46.7373, 32.8128", "46,7373 / 32,8128", "46.7373 32.8128"]
lat_lon_order = 'LatLon' #@param ['LatLon', 'LonLat']
perctl = "75" #@param [50, 65, 75, 95]
zoom_start = 17 #@param {type:"slider", min:11, max:18, step:1}

coord_format_id = []
for i,_ in enumerate(format_pattern):
    if coord_format == format_pattern[i]:
        coord_format_id = i
        break

perctl = float(perctl)

print(f'Формат координат: {coord_format}')
print(f'Ід формата координат: {coord_format_id}')
print(f'Порядок координат: {lat_lon_order}')
print(f'Персентиль: {perctl}')
print(f'Стартовий зум мапи: {zoom_start}')

"""## Зразки вхідного тексту

Десяткова крапка і кома між значеннями (**coord_format_id = 0**):

> (44.6857, 33.56173); (44.68599, 33.56555); ...  

Десяткова кома і дріб (slash) між значеннями (**coord_format_id = 1**):

> Lorem ipsum dolor sit 46,736906/ 32,810302 adipiscin, do 46,737364/  32,812807 eiusmod ...

Десяткова крапка і пробіл (**coord_format_id = 2**):

> АБВГД 48.01388889 38.79638889 07:59 АБВГД 48.01416667 38.90555556 07:53 ...
"""

#@title СКОПІЮЙТЕ ВХІДНИЙ ТЕКСТ СЮДИ:

text = '49.698824, 37.142584  (MGRS): 49.698164, 37.151901' #@param {type:"string"}

text

"""## Розрахунок"""

map = centroid_main(text, coord_format_id=coord_format_id, perctl=perctl, zoom_start=zoom_start)

"""## Візуалізація"""

map